# Generated by Django 5.2.2 on 2025-06-11 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录ID')),
                ('name', models.CharField(max_length=50, verbose_name='班级名称')),
                ('address', models.CharField(max_length=50, verbose_name='班级位置')),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学生学号')),
                ('name', models.CharField(max_length=30, verbose_name='学生姓名')),
                ('gender', models.CharField(max_length=2, verbose_name='学生性别')),
                ('age', models.IntegerField(verbose_name='学生年龄')),
                ('intoTime', models.CharField(db_column='into_time', max_length=19, verbose_name='入学时间')),
                ('grade', models.ForeignKey(db_column='grade_id', on_delete=django.db.models.deletion.CASCADE, to='app.grades')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
